Script started on Mon 15 Mar 2021 10:09:21 PM PDT
]0;lilyaj@crystalcove:~/hw5[lilyaj@crystalcove ~/hw5]$ vi[K[Kmake all
make: Nothing to be done for `all'.
]0;lilyaj@crystalcove:~/hw5[lilyaj@crystalcove ~/hw5]$ ./TicTacWowWeeWow 
Welcome to Secure-Tic-Tac-Whoa!
1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 2

Would you like to play 1.Inky, 2.Blinky, or 3.Pinky?
Enter a number 1-3: 1
Human v. Inky game started
C  | | 
  -----
B  | | 
  -----
A  | | 
  1 2 3
Player 1, please choose your move:A1
C  | | 
  -----
B  | | 
  -----
A X[0m| | 
  1 2 3
AI is choosing its move:
C O[0m| | 
  -----
B  | | 
  -----
A X[0m| | 
  1 2 3
Player 1, please choose your move:A2
C O[0m| | 
  -----
B  | | 
  -----
A X[0m|X[0m| 
  1 2 3
AI is choosing its move:
C O[0m|O[0m| 
  -----
B  | | 
  -----
A X[0m|X[0m| 
  1 2 3
Player 1, please choose your move:A3
C O[0m|O[0m| 
  -----
B  | | 
  -----
A X[0m|X[0m|X[0m
  1 2 3
Player 1 wins! Game Over!

1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 2

Would you like to play 1.Inky, 2.Blinky, or 3.Pinky?
Enter a number 1-3: 2
Human v. Blinky game started
C  | | 
  -----
B  | | 
  -----
A  | | 
  1 2 3
Player 1, please choose your move:A1
C  | | 
  -----
B  | | 
  -----
A X[0m| | 
  1 2 3
AI is choosing its move:
C O[0m| | 
  -----
B  | | 
  -----
A X[0m| | 
  1 2 3
Player 1, please choose your move:B1
C O[0m| | 
  -----
B X[0m| | 
  -----
A X[0m| | 
  1 2 3
AI is choosing its move:
C O[0m| | 
  -----
B X[0m| |O[0m
  -----
A X[0m| | 
  1 2 3
Player 1, please choose your move:B2
C O[0m| | 
  -----
B X[0m|X[0m|O[0m
  -----
A X[0m| | 
  1 2 3
AI is choosing its move:
C O[0m| | 
  -----
B X[0m|X[0m|O[0m
  -----
A X[0m|O[0m| 
  1 2 3
Player 1, please choose your move:C3
C O[0m| |X[0m
  -----
B X[0m|X[0m|O[0m
  -----
A X[0m|O[0m| 
  1 2 3
Player 1 wins! Game Over!

1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 2

Would you like to play 1.Inky, 2.Blinky, or 3.Pinky?
Enter a number 1-3: 3
Human v. Pinky game started
C  | | 
  -----
B  | | 
  -----
A  | | 
  1 2 3
Player 1, please choose your move:A B1
C  | | 
  -----
B X[0m| | 
  -----
A  | | 
  1 2 3
AI is choosing its move:
C  | |O[0m
  -----
B X[0m| | 
  -----
A  | | 
  1 2 3
Player 1, please choose your move:B2
C  | |O[0m
  -----
B X[0m|X[0m| 
  -----
A  | | 
  1 2 3
AI is choosing its move:
C  | |O[0m
  -----
B X[0m|X[0m|O[0m
  -----
A  | | 
  1 2 3
Player 1, please choose your move:C1
C X[0m| |O[0m
  -----
B X[0m|X[0m|O[0m
  -----
A  | | 
  1 2 3
AI is choosing its move:
C X[0m| |O[0m
  -----
B X[0m|X[0m|O[0m
  -----
A O[0m| | 
  1 2 3
Player 1, please choose your move:A3
C X[0m| |O[0m
  -----
B X[0m|X[0m|O[0m
  -----
A O[0m| |X[0m
  1 2 3
Player 1 wins! Game Over!

1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 4
Thanks for playing. Exiting game...
]0;lilyaj@crystalcove:~/hw5[lilyaj@crystalcove ~/hw5]$ valgrind ./Tic
TicTacWowWeeWow*        TicTacWowWeeWow.c       TicTacWowWeeWow.o       TicTacWowWeeWow.script  TicTacWowWeeWow.txt     
]0;lilyaj@crystalcove:~/hw5[lilyaj@crystalcove ~/hw5]$ valgrind ./TicTacWowWeeWow
==42393== Memcheck, a memory error detector
==42393== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==42393== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==42393== Command: ./TicTacWowWeeWow
==42393== 
Welcome to Secure-Tic-Tac-Whoa!
1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 2

Would you like to play 1.Inky, 2.Blinky, or 3.Pinky?
Enter a number 1-3: 1
Human v. Inky game started
C  | | 
  -----
B  | | 
  -----
A  | | 
  1 2 3
Player 1, please choose your move:A1
C  | | 
  -----
B  | | 
  -----
A X[0m| | 
  1 2 3
AI is choosing its move:
C O[0m| | 
  -----
B  | | 
  -----
A X[0m| | 
  1 2 3
Player 1, please choose your move:A2
C O[0m| | 
  -----
B  | | 
  -----
A X[0m|X[0m| 
  1 2 3
AI is choosing its move:
C O[0m|O[0m| 
  -----
B  | | 
  -----
A X[0m|X[0m| 
  1 2 3
Player 1, please choose your move:A3
C O[0m|O[0m| 
  -----
B  | | 
  -----
A X[0m|X[0m|X[0m
  1 2 3
Player 1 wins! Game Over!

1. Start New Game (Human v. Human)
2. Start New Game (Human v. AI)
3. Game Settings
4. Exit Game
Choose Option: 4
Thanks for playing. Exiting game...
==42393== 
==42393== HEAP SUMMARY:
==42393==     in use at exit: 120 bytes in 5 blocks
==42393==   total heap usage: 7 allocs, 2 frees, 152 bytes allocated
==42393== 
==42393== LEAK SUMMARY:
==42393==    definitely lost: 0 bytes in 0 blocks
==42393==    indirectly lost: 0 bytes in 0 blocks
==42393==      possibly lost: 0 bytes in 0 blocks
==42393==    still reachable: 120 bytes in 5 blocks
==42393==         suppressed: 0 bytes in 0 blocks
==42393== Rerun with --leak-check=full to see details of leaked memory
==42393== 
==42393== For counts of detected and suppressed errors, rerun with: -v
==42393== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;lilyaj@crystalcove:~/hw5[lilyaj@crystalcove ~/hw5]$ exit
exit

Script done on Mon 15 Mar 2021 10:11:18 PM PDT
